/**
 * Share Module — Screenshot · Download · Share
 *
 * Features:
 *  · Lazy-loads html2canvas only when first used (no initial perf hit)
 *  · Draws watermark directly on captured canvas (no DOM manipulation)
 *  · Download as high-quality PNG (scale:2)
 *  · Native Web Share API (image on supporting devices)
 *  · WhatsApp text fallback
 *  · Clipboard text fallback
 *
 * Wires: #screenshotBtn  #downloadBtn  #shareBtn
 */

import { showToast } from './toast.js';

const WATERMARK_TEXT = 'Generated by Ajinkya2OP BGMI Sensitivity Pro 🔥';
const H2C_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js';

let _h2cReady = false;

// ── Load html2canvas on demand ────────────────────────────
async function loadH2C() {
  if (_h2cReady || window.html2canvas) { _h2cReady = true; return; }
  return new Promise((resolve, reject) => {
    const s  = document.createElement('script');
    s.src    = H2C_CDN;
    s.async  = true;
    s.onload = () => { _h2cReady = true; resolve(); };
    s.onerror = () => reject(new Error('html2canvas failed to load'));
    document.head.appendChild(s);
  });
}

// ── Capture #rc card → canvas with watermark ─────────────
async function captureResultCard() {
  await loadH2C();

  const el = document.getElementById('rc');
  if (!el) return null;

  const canvas = await window.html2canvas(el, {
    backgroundColor: '#0d1120',
    scale:           2,
    useCORS:         true,
    logging:         false,
    // Exclude share buttons from capture so they don't appear in image
    ignoreElements: (node) =>
      node.id === 'shareActs' ||
      node.classList?.contains('share-acts'),
  });

  // ── Draw watermark on captured canvas ──────────────────
  const ctx      = canvas.getContext('2d');
  const fontSize = Math.max(14, Math.floor(canvas.width * 0.018));
  const padY     = fontSize * 1.6;

  // Subtle semi-transparent bar at bottom
  ctx.fillStyle = 'rgba(0,0,0,0.38)';
  ctx.fillRect(0, canvas.height - padY * 1.4, canvas.width, padY * 1.4);

  // Watermark text
  ctx.font         = `600 ${fontSize}px 'Rajdhani', sans-serif`;
  ctx.fillStyle    = 'rgba(0,245,160,0.6)';
  ctx.textAlign    = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(WATERMARK_TEXT, canvas.width / 2, canvas.height - padY * 0.65);

  return canvas;
}

// ── Download PNG ──────────────────────────────────────────
async function downloadImage() {
  const btn = document.getElementById('downloadBtn');
  if (btn) { btn.textContent = '⏳ Capturing…'; btn.disabled = true; }

  try {
    const canvas  = await captureResultCard();
    if (!canvas)  { showToast('❌ Nothing to capture yet.', 'error'); return; }

    const dataUrl = canvas.toDataURL('image/png', 1.0);
    const a       = document.createElement('a');
    a.href        = dataUrl;
    a.download    = `bgmi-sensitivity-ajinkya2op-${Date.now()}.png`;
    a.click();

    showToast('✅ Image downloaded!', 'success');
  } catch (err) {
    showToast('❌ Download failed. Try Copy instead.', 'error');
  } finally {
    if (btn) { btn.textContent = '⬇️ Download'; btn.disabled = false; }
  }
}

// ── Open screenshot preview (new tab) ────────────────────
async function openScreenshot() {
  const btn = document.getElementById('screenshotBtn');
  if (btn) { btn.textContent = '⏳ Rendering…'; btn.disabled = true; }

  try {
    const canvas = await captureResultCard();
    if (!canvas) { showToast('❌ Nothing to capture yet.', 'error'); return; }

    // Open in new tab so user can long-press save on mobile
    const dataUrl  = canvas.toDataURL('image/png', 1.0);
    const newTab   = window.open();
    if (newTab) {
      newTab.document.write(
        `<html><head><title>BGMI Sensitivity — Ajinkya2OP</title></head>` +
        `<body style="margin:0;background:#080b12;display:flex;justify-content:center;align-items:flex-start;padding:20px">` +
        `<img src="${dataUrl}" style="max-width:100%;border-radius:12px;box-shadow:0 8px 40px rgba(0,245,160,.2)"/></body></html>`,
      );
      newTab.document.close();
    } else {
      // Pop-up blocked — fall back to direct download
      await downloadImage();
    }
  } catch {
    showToast('❌ Screenshot failed. Try Download.', 'error');
  } finally {
    if (btn) { btn.textContent = '📸 Screenshot'; btn.disabled = false; }
  }
}

// ── Share ─────────────────────────────────────────────────
async function share() {
  const btn  = document.getElementById('shareBtn');
  const text = document.getElementById('ot')?.textContent ?? '';
  if (!text.trim()) { showToast('Generate your sensitivity first!', 'warn'); return; }

  const title    = 'My BGMI Sensitivity by Ajinkya2OP 🔥';
  const shareText = `${title}\n\n${text}\n\nGenerated at: ajinkya2op.netlify.app`;

  if (btn) { btn.textContent = '⏳…'; btn.disabled = true; }

  try {
    // ── Try native share with image ──────────────────────
    if (navigator.share) {
      try {
        // Build image file for share
        const canvas   = await captureResultCard();
        const dataUrl  = canvas?.toDataURL('image/png', 1.0);

        if (dataUrl && navigator.canShare) {
          const blob = await (await fetch(dataUrl)).blob();
          const file = new File([blob], 'bgmi-sensitivity.png', { type: 'image/png' });
          if (navigator.canShare({ files: [file] })) {
            await navigator.share({ title, text: shareText, files: [file] });
            showToast('✅ Shared!', 'success');
            return;
          }
        }
        // Text-only share fallback
        await navigator.share({ title, text: shareText });
        showToast('✅ Shared!', 'success');
        return;
      } catch (e) {
        if (e.name === 'AbortError') return; // User cancelled — not an error
      }
    }

    // ── WhatsApp fallback ────────────────────────────────
    const waUrl = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
    window.open(waUrl, '_blank', 'noopener');
    showToast('📤 Opening WhatsApp…', 'default');

  } catch {
    // ── Copy to clipboard as last resort ─────────────────
    try {
      await navigator.clipboard.writeText(shareText);
      showToast('📋 Sensitivity copied — paste anywhere to share!', 'success', 4000);
    } catch {
      showToast('❌ Share failed. Use Copy instead.', 'error');
    }
  } finally {
    if (btn) { btn.textContent = '🔗 Share'; btn.disabled = false; }
  }
}

// ── Public init — call once from main.js ─────────────────
export function initShareButtons() {
  document.getElementById('screenshotBtn')?.addEventListener('click', openScreenshot);
  document.getElementById('downloadBtn')?.addEventListener('click', downloadImage);
  document.getElementById('shareBtn')?.addEventListener('click', share);
}
